apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}-cm
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
data:
  probe-proxysql.bash: |
{{ tpl (.Files.Get "files/probe-proxysql.bash") . | indent 4 }}
  {{- if and .Values.eventsLog.enabled .Values.eventsLog.logrotate.enabled }}
  cleanlogs.bash: |
{{ tpl (.Files.Get "files/cleanlogs.bash") . | indent 4 }}
  {{- end }}
