apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}-secret
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
stringData:
  proxysql.cnf: |
    {{- tpl .Values.config.template . | nindent 4 }}
  ADMIN_PASSWORD: {{ include "proxysql.pwd" .Values.credentials.admin }}
  ADMIN_USER: {{ .Values.credentials.admin.user }}
  RADMIN_PASSWORD: {{ include "proxysql.pwd" .Values.credentials.radmin }}
  RADMIN_USER: {{ .Values.credentials.radmin.user }}
